### PR TITLE
docs: add functions to readme

### PR DESCRIPTION
**Pull request by cemremengu**
Add function examples to readme

### CODE REVIEW

**Review by ikrivosheev — APPROVED** [review]
@cemremengu thank you! LGTM! @billy1624 @tyt2y3 can you also review?

**Comment by ikrivosheev** [comment]
@billy1624 @tyt2y3 can you review PR?

**Comment by tyt2y3** [comment]
Looks good, but I think sum/max/min/avg/abs can be combined. These aggregate operators are all "the same".

**Review by billy1624 — COMMENTED** [review]
Btw... remember to update [`lib.rs`](https://github.com/SeaQL/sea-query/blob/master/src/lib.rs) (crate level docs) as well. We should always update `lib.rs` then execute [`cargo-readme.sh`](https://github.com/SeaQL/sea-query/blob/master/build-tools/cargo-readme.sh) script to copy the changes to README.md

**Comment by tyt2y3** [comment]
> 

True

**Comment by cemremengu** [comment]
Sorry for the delay, I will be able to do the requested changes next week when I get back from holiday

**Review by billy1624 — COMMENTED** [review]
Btw... we could also add a link to Postgres specific functions: https://docs.rs/sea-query/latest/sea_query/func/struct.PgFunc.html

**Comment by cemremengu** [comment]
These examples seem to be merged with recent commits so closing in favor. Feel free to re-open if needed.

**Comment by billy1624** [comment]
Thanks again for the contributions!! @cemremengu

**Comment by tyt2y3** [comment]
Yes I cherry-picked some bits to master

**Pull request closed without merging**
