### PR TITLE
Add is / is_not to Expr

### PR DESCRIPTION
**Pull request by Sytten**
For Sqlite, they are the same as `eq` and `neq` but treat NULL differently.
I put them behind a flag since I don't think other DBMS allow random values with those operators.

## Adds

- `IS` and `IS NOT` operators for `Sqlite`

### CODE REVIEW

**Comment by ikrivosheev** [comment]
@Sytten thank you for the PR! 
I don't understand... You add a doc test for Postgres backend and for MySQL backend but hide `is` under the feature flag: `backend-sqlite`.

**Comment by Sytten** [comment]
Right I will remove it, I did a stupid copy paste

**Comment by ikrivosheev** [comment]
@Sytten as I know in postgresql we can use `IS TRUE` for example. Also we didn`t want to add feature flag to `Expr`.

**Comment by Sytten** [comment]
So how do we wish to proceed? Just leave it open for any backend?

**Comment by tyt2y3** [comment]
Yes. We don't actually feature guard the frontend in general.

**Review by ikrivosheev — APPROVED** [review]
@Sytten thank you! LGTM!

**Comment by tyt2y3** [comment]
Thank you all

**Pull request merged**
