### PR TITLE
[Draft] support upsert sql 

### PR DESCRIPTION
**Pull request by baoyachi**
Inprogres work for https://github.com/SeaQL/sea-orm/issues/187

### CODE REVIEW

**Comment by billy1624** [comment]
Hey @baoyachi, I have converted this PR to draft. You can mark this as "Ready for Review" once it's ready :)

**Comment by baoyachi** [comment]
Sorry.
I deleted the source branch master myself. Unexpectedly, it triggered the closing of the pull request of GitHub.
I have changed the master branch to the upsert branch。


> Hey @baoyachi, what happened?

Sorry.
I deleted the source branch master myself. Unexpectedly, it triggered the closing of the pull request of GitHub.
I have changed the master branch to the upsert branch。

**Comment by billy1624** [comment]
It's fine. Please open another PR for this :P

**Comment by baoyachi** [comment]
> It's fine. Please open another PR for this :P

The new pr :https://github.com/SeaQL/sea-query/pull/167

**Pull request closed without merging**
