### PR TITLE
issues-280 Rewrite drivers using proc-macro

### PR DESCRIPTION
**Pull request by ikrivosheev**
## PR Info

- Closes <https://github.com/SeaQL/sea-query/issues/280>

## Fixes

Rewrite drivers for: `rusqlite`, `sqlx_*` from `macro_rules` to `proc-macro`. In `proc-macro` we can use `cfg` instead of blank method for types, which enable by crate features and fix: https://github.com/SeaQL/sea-query/issues/280

I add `cfg` for implementation methods which enable by feature like: `with-*`.

## Breaking Changes

1. Remove methods `Value::is_json` and `Value::as_ref_json` when feature: **with-json** is disabled
2. Remove methods `Value::is_time_*` and `Value::as_ref_time_*` when feature: **with-time** is disabled
3. Remove methods `Value::is_chrono_*` and `Value::as_ref_chrono*` when feature: **with-chrono** is disabled
4. Remove methods `Value::is_decimal`, `Value::as_ref_decimal` and `Value::decimal_to_f64` when feature: **with-rust_decimal** is disabled
5. Remove methods `Value::is_big_decimal`, `Value::as_ref_big_decimal` and `Value::big_decimal_to_f64` when feature: **with-bigdecimal** is disabled
6. Remove methods `Value::is_uuid` and `Value::as_ref_uuid` when feature: **with-uuid** is disabled
7. Remove methods `Value::is_array` and `Value::as_ref_array` when feature: **postgres-array** is disabled

### CODE REVIEW

**Comment by tyt2y3** [comment]
Thank you. This looked extremely brilliant!
Does that mean the examples stay the same with no change?
Btw we might want to add it to the workspace? https://github.com/SeaQL/sea-query/blob/master/Cargo.toml#L2
The only nitpick might be.. can we name the crate `sea-query-drivers` ?

**Comment by ikrivosheev** [comment]
@tyt2y3 thank you for review. Done, renamed!

Yes, all examples work as before. But, for example, if feature: `with-json` does not enable, `Value` does not have methods: `is_json`, `as_json_ref`.

**Comment by ikrivosheev** [comment]
@tyt2y3 i rebase branch with master.

**Comment by tyt2y3** [comment]
Thank you for the explanation. I think it also obeys to the rule of "feature addition"

**Comment by ikrivosheev** [comment]
@tyt2y3 what should i do?

**Comment by tyt2y3** [comment]
Oh, nothing more has to be done. I was thinking the scenario where two downstream creates each with a different feature set.

**Comment by ikrivosheev** [comment]
I have seen similar approach in other libraries (for example [syn](https://docs.rs/syn/latest/syn/), when features add new functions and methods into crate and types. It is very comfortable and works well in rust.

**Comment by ikrivosheev** [comment]
@billy1624 @tyt2y3 I have corrected the description

**Pull request merged**
