### PR TITLE
[sea-query-binder] enable SQLx features if and only if SQLx optional dependency is enabled

### PR DESCRIPTION
**Pull request by billy1624**
## PR Info

- Dependents:
  - https://github.com/SeaQL/sea-orm/pull/1213

## Bug Fixes

- [x] This allows user to have a SeaORM entity crate without enabling any db driver

<details>

<summary>
The error without `sqlx?/xxx`
</summary>

```
➜ cargo b
    Blocking waiting for file lock on package cache
    Blocking waiting for file lock on package cache
    Blocking waiting for file lock on package cache
   Compiling sea-query-binder v0.2.1
error[E0004]: non-exhaustive patterns: `sea_query::Value::Json(_)`, `sea_query::Value::ChronoDate(_)`, `sea_query::Value::ChronoTime(_)` and 10 more not covered
   --> /Users/billy/.cargo/registry/src/github.com-1ecc6299db9ec823/sea-query-binder-0.2.1/src/sqlx_mysql.rs:9:19
    |
9   |             match arg {
    |                   ^^^ patterns `sea_query::Value::Json(_)`, `sea_query::Value::ChronoDate(_)`, `sea_query::Value::ChronoTime(_)` and 10 more not covered
    |
note: `sea_query::Value` defined here
   --> /Users/billy/.cargo/registry/src/github.com-1ecc6299db9ec823/sea-query-0.27.1/src/value.rs:121:1
    |
121 | pub enum Value {
    | ^^^^^^^^^^^^^^
    = note: the matched value is of type `sea_query::Value`
help: ensure that all possible cases are being handled by adding a match arm with a wildcard pattern as shown, or multiple match arms
    |
51  ~                 }
52  +                 _ => todo!()
    |

error[E0004]: non-exhaustive patterns: `sea_query::Value::Json(_)`, `sea_query::Value::ChronoDate(_)`, `sea_query::Value::ChronoTime(_)` and 10 more not covered
   --> /Users/billy/.cargo/registry/src/github.com-1ecc6299db9ec823/sea-query-binder-0.2.1/src/sqlx_postgres.rs:25:19
    |
25  |             match arg {
    |                   ^^^ patterns `sea_query::Value::Json(_)`, `sea_query::Value::ChronoDate(_)`, `sea_query::Value::ChronoTime(_)` and 10 more not covered
    |
note: `sea_query::Value` defined here
   --> /Users/billy/.cargo/registry/src/github.com-1ecc6299db9ec823/sea-query-0.27.1/src/value.rs:121:1
    |
121 | pub enum Value {
    | ^^^^^^^^^^^^^^
    = note: the matched value is of type `sea_query::Value`
help: ensure that all possible cases are being handled by adding a match arm with a wildcard pattern as shown, or multiple match arms
    |
67  ~                 }
68  +                 _ => todo!()
    |

error[E0004]: non-exhaustive patterns: `sea_query::Value::Json(_)`, `sea_query::Value::ChronoDate(_)`, `sea_query::Value::ChronoTime(_)` and 10 more not covered
   --> /Users/billy/.cargo/registry/src/github.com-1ecc6299db9ec823/sea-query-binder-0.2.1/src/sqlx_sqlite.rs:9:19
    |
9   |             match arg {
    |                   ^^^ patterns `sea_query::Value::Json(_)`, `sea_query::Value::ChronoDate(_)`, `sea_query::Value::ChronoTime(_)` and 10 more not covered
    |
note: `sea_query::Value` defined here
   --> /Users/billy/.cargo/registry/src/github.com-1ecc6299db9ec823/sea-query-0.27.1/src/value.rs:121:1
    |
121 | pub enum Value {
    | ^^^^^^^^^^^^^^
    = note: the matched value is of type `sea_query::Value`
help: ensure that all possible cases are being handled by adding a match arm with a wildcard pattern as shown, or multiple match arms
    |
51  ~                 }
52  +                 _ => todo!()
    |

For more information about this error, try `rustc --explain E0004`.
error: could not compile `sea-query-binder` due to 3 previous errors
```

</details>

### CODE REVIEW

**Review by ikrivosheev — APPROVED** [review]

**Comment by tyt2y3** [comment]
Good stuff

**Comment by tyt2y3** [comment]
Yes, sounds doable

**Comment by tyt2y3** [comment]
This can just be a minor bump to sea-query-binder, and no new version is needed on sea-query

**Comment by billy1624** [comment]
Okay, then I will wait on the release of SeaQuery before jumping back into https://github.com/SeaQL/sea-orm/pull/1213.

**Comment by tyt2y3** [comment]
https://crates.io/crates/sea-query-binder/versions I released

**Comment by ikrivosheev** [comment]
@tyt2y3, thank you!

**Comment by billy1624** [comment]
That was fast

**Pull request merged**
