### PR TITLE
issues-356 Upgrade time to 0.3, bigdecimal to 0.3, sqlx to 0.6, rusql…

### PR DESCRIPTION
**Pull request by ikrivosheev**
## PR Info

- Closes https://github.com/SeaQL/sea-query/issues/356

## Breaking Changes

- Drop support `time` 0.2
- Drop support `bigdecimal` 0.2
- Drop support `sqlx` 0.5
- Drop support `ipnetwork` 0.19

## Changes

- Upgrade `time` to 0.3
- Upgrade `bigdecimal` to 0.3
- Upgrade `ipnetwork` to 0.19
- Upgrade `sqlx` to 0.6

## P.S

At the moment **rusqlite** does not work, because we are waiting new release.

### CODE REVIEW

**Comment by tyt2y3** [comment]
oh sorry! I am also working on that

**Comment by tyt2y3** [comment]
Does master actually work now?

**Comment by ikrivosheev** [comment]
@tyt2y3 yes!

**Comment by tyt2y3** [comment]
Actually, the time_format module you made is really useful!

**Comment by tyt2y3** [comment]
Can't believe `time` had made such a change.

**Pull request closed without merging**
