### PR TITLE
support &String type from to Value

### LINKED ISSUE #537: Optimize：the trait `std::convert::From<&std::string::String>` is not implemented for `sea_orm::Value`
sea_orm::Value not support &String, This can be optimized.

caused error sea-orm version:
```bash
sea-orm v0.9.3
```
E.g, the key code
```bash
...
    |
354 |             .filter(rules::Column::BizType.eq(&rule))
    |                                                      -- ^^^^^^^^^ the trait `std::convert::From<&std::string::String>` is not implemented for `sea_orm::Value`
    |                                                      |
    |                                                      required by a bound introduced by this call
    |
    = note: required for `&std::string::String` to implement `Into<sea_orm::Value>`
note: required by a bound in `sea_orm::ColumnTrait::eq`
   --> /Users/baoyachi/.cargo/registry/src/sea-orm-0.9.3/src/entity/column.rs:161:5
    |
161 |     bind_oper_with_enum_casting!(eq, Equal);
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ required by this bound in `sea_orm::ColumnTrait::eq`
    = note: this error originates in the macro `bind_oper_with_enum_casting` (in Nightly builds, run with -Z macro-backtrace for more info)
help: consider dereferencing here

```

### PR DESCRIPTION
**Pull request by baoyachi**
fix #537

### CODE REVIEW

**Review by billy1624 — COMMENTED** [review]
Hey @baoyachi, nice refactoring! Yeah, I don't think the explicit named lifetime is a must :)

**Comment by ikrivosheev** [comment]
@baoyachi hello. I agree with @billy1624 with remove named lifetime. But I don't this that add `From<&String>`  is good idea.

Small example:

```
fn test(a: &str) {
    println!("{}", a)
}

fn main() {
    let string = String::from("1234");
    let a: &String = &string;
    
    test(a);
}
```

**Comment by baoyachi** [comment]
> @baoyachi hello. I agree with @billy1624 with remove named lifetime. But I don't this that add `From<&String>` is good idea.
> 
> Small example:
> 
> ```
> fn test(a: &str) {
>     println!("{}", a)
> }
> 
> fn main() {
>     let string = String::from("1234");
>     let a: &String = &string;
>     
>     test(a);
> }
> ```

@ikrivosheev  please see this error: https://github.com/SeaQL/sea-query/issues/537#issue-1469260255

**Review by ikrivosheev — APPROVED** [review]
@baoyachi, well, it makes sense... 

@billy1624 @tyt2y3 can you look at it?

**Review by billy1624 — APPROVED** [review]
Thanks!! @baoyachi

**Pull request merged**
