### PR TITLE
Deprecated some methods

### PR DESCRIPTION
**Pull request by ikrivosheev**
## Changes

- `Expr::value` accept `Into<SimpleExpr>` instead `Into<Value>`
- `Expr::gt` accept `Into<SimpleExpr>` instead `Into<Value>`
- `Expr::gte` accept `Into<SimpleExpr>` instead `Into<Value>`
- `Expr::lt` accept `Into<SimpleExpr>` instead `Into<Value>`
- `Expr::lte` accept `Into<SimpleExpr>` instead `Into<Value>`
- `Expr::add` accept `Into<SimpleExpr>` instead `Into<Value>`
- `Expr::div` accept `Into<SimpleExpr>` instead `Into<Value>`
- `Expr::sub` accept `Into<SimpleExpr>` instead `Into<Value>`
- `Expr::modulo` accept `Into<SimpleExpr>` instead `Into<Value>`
- `Expr::left_shift` accept `Into<SimpleExpr>` instead `Into<Value>`
- `Expr::right_shift` accept `Into<SimpleExpr>` instead `Into<Value>`
- `Expr::between` accept `Into<SimpleExpr>` instead `Into<Value>`
- `Expr::not_between` accept `Into<SimpleExpr>` instead `Into<Value>`
- `Expr::is` accept `Into<SimpleExpr>` instead `Into<Value>`
- `Expr::is_not` accept `Into<SimpleExpr>` instead `Into<Value>`
- `Expr::if_null` accept `Into<SimpleExpr>` instead `Into<Value>`
- `Expr::is_in`, `Expr::is_not_in` accept `Into<SimpleExpr>` instead `Into<Value>` and convert it to `SimpleExpr::Tuple` instead `SimpleExpr::Values`

# Deprecated
- `Expr::greater_than`
- `Expr::greater_or_equal`
- `Expr::less_than`
- `Expr::less_or_equal`

### CODE REVIEW

**Comment by Razican** [comment]
As talked in Discord, it seems that the `Expr::is_in()` function makes it tricky to use custom enums, for example, to add a list of values. @billy1624 recommended using this:
```rust
Expr::col(Glyph::Id).binary(BinOper::In, Expr::tuple([Expr::cust("1"), Expr::cust("2")]))
```

But this is a bit cumbersome, so he proposed to simplify that within this PR.

**Comment by ikrivosheev** [comment]
> As talked in Discord, it seems that the `Expr::is_in()` function makes it tricky to use custom enums, for example, to add a list of values. @billy1624 recommended using this:
> 
> ```rust
> Expr::col(Glyph::Id).binary(BinOper::In, Expr::tuple([Expr::cust("1"), Expr::cust("2")]))
> ```
> 
> But this is a bit cumbersome, so he proposed to simplify that within this PR.

@Razican hello! Thank you, done

**Comment by ikrivosheev** [comment]
@billy1624 @tyt2y3 can you review the PR?

**Comment by ikrivosheev** [comment]
@billy1624 @tyt2y3 ping

**Review by tyt2y3 — APPROVED** [review]
Looking great

**Pull request merged**
