### PR TITLE
Use double quotes for quuoting identifgiers for SQLite

### LINKED ISSUE #220: Why are why you using back-ticks for sqlite identifiers instead of double quotes?
If you switch to double quotes then you avoid this sqlx [issue](https://github.com/launchbadge/sqlx/issues/1531), which would allow `RETURNING` to work for SQLite for every backend (plus you are more correct according to the SQL standard))
[SQLite keywords](https://www.sqlite.org/lang_keywords.html)

### PR DESCRIPTION
**Pull request by SpyrosRoum**
This should allow `RETURNING` to work for SQLite with sqlx 
closes #220

### CODE REVIEW

**Comment by SpyrosRoum** [comment]
I didn't realize I had to use the `--all-features` flag when testing so I kept missing some tests until the ci told me.
It should be good now

**Comment by tyt2y3** [comment]
@billy1624 Can take a look at the failed cases?

**Comment by billy1624** [comment]
> @billy1624 Can take a look at the failed tests?

I reverted the binding of array values https://github.com/SeaQL/sea-query/commit/67a8ffba1351c754aae2559051930d4fe2fe70ae

**Comment by tyt2y3** [comment]
Awesome, thank you for the diligence!

**Pull request merged**
