### PR TITLE
Fix UNIQUE table index expression syntax for sqlite

### PR DESCRIPTION
**Pull request by 05storm26**
Fixes: #226

### CODE REVIEW

**Comment by billy1624** [comment]
Hey @05storm26, thank you so much for the quick fix!

**Comment by billy1624** [comment]
I was thinking to refactor the code https://github.com/05storm26/sea-query/compare/master...billy1624:pr/227
You can cherrypick if the changes make sense to you. Thanks!

**Comment by 05storm26** [comment]
Thanks I have squashed it into the commit

**Comment by alvardes** [comment]
@billy1624 Can you merge this?

**Review by billy1624 — APPROVED** [review]
Thanks!! @05storm26

**Review by tyt2y3 — APPROVED** [review]

**Pull request merged**
