### PR TITLE
Make sea-query-driver an optional dependency

### LINKED ISSUE #323: "sea-query-driver" dependency isn't optional, loads proc macro crates
## Description

One of the things that immediately stood out to me about sea-query was: `SeaQuery is very lightweight, all dependencies are optional.`

Awesome! No waiting for long build times on procedural macros 😁

Unfortunately, this appears to not be the case -- `sea-query-driver` is a hard dependency, and it depends on `syn`, `proc_macro2`, and some of the other usual suspects of procedural macros.

It looks like it's not actually needed as part of the library, and it was likely just a mistake that the words `optional = true` and some `cfg` checks were omitted.

I have an incoming PR to remedy the situation

## Steps to Reproduce

Build `sea-query` from another project with default features disabled

### Expected Behavior

`sea-query` should be the only thing built

### Actual Behavior

`sea-query-driver` and several of its dependencies are also pulled from `crates.io` and built

### Reproduces How Often

Always

## Versions

current

### PR DESCRIPTION
**Pull request by marti4d**
Fixes #323

## PR Info

- Closes #323

## Fixes

- [x] sea-query-driver being built even with all default features disabled

### CODE REVIEW

**Comment by tyt2y3** [comment]
Nice catch!

**Comment by tyt2y3** [comment]
https://github.com/SeaQL/sea-query/releases/tag/0.24.6

**Comment by Sytten** [comment]
It should have been added to the default features though since this will break people's code...

**Comment by tyt2y3** [comment]
Thanks for pointing that out.
I think I released the correct code, but I accidentally hit the Release on GitHub before successfully pushed and so tagged the wrong version.

> It should have been added to the default features though since this will break people's code...

I think this will be fine. For example, `sqlx-mysql` will enable `sea-query-driver/sqlx-mysql` implicitly.

**Pull request merged**
