### PR TITLE
Add like and ilike for simple expr in PostgreSQL

### LINKED ISSUE #521: Allow for LIKE and ILIKE in Simple Expr
## Motivation

I need to dynamically filter various columns with the LIKE and ILIKE operators in PostgreSQL (I have no idea if other databases allow for this, I would assume they do, but I will put this behind the PostgreSQL feature). Since the LIKE and ILIKE operators cannot be used in non character data types I need to cast them before the operation.

This is currently not very convenient, this adds support for using the LIKE and ILIKE operators for simple expressions.

### PR DESCRIPTION
**Pull request by andyquinterom**
## PR Info

Closes #521 

## New Features

- [x] Allows the use of (`NOT`) `LIKE`, `ILIKE` on a `SimpleExpr`

### CODE REVIEW

**Comment by ikrivosheev** [comment]
@andyquinterom hello! Thank you for the pr, but I already do this: https://github.com/SeaQL/sea-query/pull/519

**Comment by andyquinterom** [comment]
> @andyquinterom hello! Thank you for the pr, but I have already done this: #519

Perfect! Any idea of a timeline for merging your changes?

**Comment by ikrivosheev** [comment]
> > @andyquinterom hello! Thank you for the pr, but I have already done this: #519
> 
> Perfect! Any idea of a timeline for merging your changes?

When @billy1624 and @tyt2y3 review my changes)

**Comment by ikrivosheev** [comment]
@andyquinterom I am so sorry, my mistake. I will reopen your PR and merge it after some comment!

**Comment by ikrivosheev** [comment]
@andyquinterom can you resolve conflicts?

**Comment by tyt2y3** [comment]
Since this is a postgres-only feature, I think it'd be better to be moved to `PgExpr` following @ikrivosheev recent refactoring.

**Pull request merged**
