### PR TITLE
Fix postgres driver

### PR DESCRIPTION
**Pull request by ikrivosheev**
## PR Info

Postgres driver tests are failed.

## Fixes

- Postgres driver

### CODE REVIEW

**Review by billy1624 — APPROVED** [review]
Thanks!! @ikrivosheev I was going to dig in and solve it

**Comment by yotamofek** [comment]
Would be great to get this in a release, 0.26 is completely broken for my use case 🙌

**Comment by billy1624** [comment]
Hey @yotamofek, sorry for the inconvenience. We'll release this as part of 0.26.1

**Comment by tyt2y3** [comment]
Sad. Is there something we can do to catch these errors in our CI?

**Comment by ikrivosheev** [comment]
> Sad. Is there something we can do to catch these errors in our CI?

We catch this error now)

**Comment by ikrivosheev** [comment]
I found this bug when I did another issue.

**Comment by tyt2y3** [comment]
https://github.com/SeaQL/sea-query/releases/tag/0.26.2

**Pull request merged**
