### PR TITLE
add mod, lshift & rshift binary operations

### LINKED ISSUE #418: Missing BinaryOperators (modulo, lshift, rshift)
## Motivation

The current query builder has no way, besides custom expressions, to build queries containing modulo or shift operations.

## Additional Information

Since all the three currently supported backends (MySQL, PostgreSQL & SQLite) support all those operators they should not prove to be much of an effort to implement. (I would do it myself, but im neither familiar with the codebase nor do I have the time to do so)

### PR DESCRIPTION
**Pull request by tooboredtocode**
## PR Info

I'm not familiar with the structure of the test folder, so I did not add any tests, the PR should be self explanatory though.

The only thing that could be added besides tests, is shortcuts for smaller operations to the Expr impl

- Closes #418 

## Adds

- [X] The following binary operations:
   - Modulo
   - Left Shift
   - Right Shift

### CODE REVIEW

**Review by ikrivosheev — COMMENTED** [review]
@tooboredtocode hello! Thank you for the PR! Can you add helpers to expr.rs and some doc tests?)

**Comment by tooboredtocode** [comment]
@ikrivosheev done

**Review by ikrivosheev — APPROVED** [review]
@tooboredtocode thank you! LGTM!

**Review by tyt2y3 — APPROVED** [review]
Thank you both!

**Pull request merged**
