### PR TITLE
issues-320 Remove deprecated methods

### PR DESCRIPTION
**Pull request by ikrivosheev**
## PR Info

- Closes https://github.com/SeaQL/sea-query/issues/320

## Breaking Changes

- Remove breaking methods

### CODE REVIEW

**Comment by tyt2y3** [comment]
Cool. Is this all you want to remove?

**Comment by ikrivosheev** [comment]
> Cool. Is this all you want to remove?

@tyt2y3 yes, this is all deprecated methods.

**Review by billy1624 — APPROVED** [review]
Awesome! Thanks!! @ikrivosheev

**Review by tyt2y3 — APPROVED** [review]
Thank you

**Pull request merged**
