### PR TITLE
Add pgvector type

### PR DESCRIPTION
**Pull request by 28Smiles**
Once this gets merged i'll clean the implementations of the feature in sea-orm and sea-schema. I tested the feature with my forks.

## New Features

- [x] Add support for the postgres vector extension

## Breaking Changes

Exhaustive columtype matching will break

## Changes

- [x] Add new value variant named Vector and Column Type

### CODE REVIEW

**Comment by tyt2y3** [comment]
Thank you for your contribution. You have many commits!

**Comment by tyt2y3** [comment]
NO problem, I'll take some time to review it

**Comment by 28Smiles** [comment]
@tyt2y3 Since i really want to stop using my own forks for this feature, it would be nice to get some progress here. Is there anything i am able to do?

**Comment by tyt2y3** [comment]
sorry for the delay. can you rebase this branch onto latest master?

**Comment by tyt2y3** [comment]
it looks pretty save, everything is behind a feature guard 👍

**Comment by 28Smiles** [comment]
@tyt2y3 needed to fix the version should be done now

**Review by tyt2y3 — APPROVED** [review]
Thank you for your patience. will merge and release soon

**Comment by dattito** [comment]
any progress for the feature in sea-orm? Would be very happy to use it in there, but unfortunately I don't have enough experience myself to implement it

**Comment by 28Smiles** [comment]
> any progress for the feature in sea-orm? Would be very happy to use it in there, but unfortunately I don't have enough experience myself to implement it

I have a pull request for the next layer [sea-schema](https://github.com/SeaQL/sea-schema/pull/137) if that is merged we can merge into sea-orm. You may just use my fork until then.

**Pull request merged**
