### PR TITLE
Add support for ESCAPE

### PR DESCRIPTION
**Pull request by Sytten**
Hello!
First contribution here :)
I am unsure if the way I implemented it is correct (specially in the Expr) but it does work as expected.

### CODE REVIEW

**Comment by tyt2y3** [comment]
Thank you so much for your contribution. I have a puzzle, why is the `\` in the last don't have to be escaped themselves?

```SQL
SELECT `character` FROM `character` WHERE `character` LIKE 'A' ESCAPE '\'
```
vs

```SQL
SELECT `character` FROM `character` WHERE `character` LIKE 'A' ESCAPE '\\'
```

**Comment by Sytten** [comment]
I think it will escape it automatically? I compared it against an r string so thats why it might be misleading. AFAIK you dont need to escape it further than that.
We used a custom expression before I wrote that and it didnt require an explicit escape. I think it might be because the input is a char not a string?
I will test further to make sure.

**Comment by ikrivosheev** [comment]
@Sytten do you want to finish this PR?

**Comment by Sytten** [comment]
I still need it but I have not had the time, I will circle back today and let you know.

**Comment by ikrivosheev** [comment]
@Sytten if you want, I can do this PR.

**Comment by Sytten** [comment]
@ikrivosheev @tyt2y3 @billy1624 
I fixed the PR to support the latest version.
It works correctly, but I am not sure if we should merge as is since the escape only makes sense when following a like so I think a separate struct for Like would be better (but it would most likely be a breaking change).
Maybe @ikrivosheev you want to take a shot at it?

**Comment by ikrivosheev** [comment]
@tyt2y3 @billy1624 perhaps we can transform `BinOper::Like` -> 
```
pub struct Like {
    pattern: String,
    escape: Option<String>
}
```

and move to `SimpleExpr`? I cannot image how it makes as part of `BinOper`

**Comment by billy1624** [comment]
For me API wise, current API is better

```rust
.and_where(Expr::col(Char::Character).like("A").escape('\\'))
```

If we require user to specify `ESCAPE` when constructing `LIKE`, unavoidably the API would be like

```rust
.and_where(Expr::col(Char::Character).like("A"))
.and_where(Expr::col(Char::Character).like_escape("A", '\\'))
```

**Comment by Sytten** [comment]
Agreed the API would not change but the return type of like would.
The problem with the current api is you can write:
```rust
.and_where(Expr::col(Char::Character).escape('\ \'))
```
Which is not valid.

**Comment by ikrivosheev** [comment]
@billy1624 @Sytten I think we can safe API, no problem)

**Comment by Sytten** [comment]
Do you want to take it over @ikrivosheev?

**Comment by ikrivosheev** [comment]
@Sytten can I merge you PR into internal branch (of course with save your commits) and continue work in internal branch?

**Comment by Sytten** [comment]
Go ahead!

**Comment by ikrivosheev** [comment]
@Sytten https://github.com/SeaQL/sea-query/pull/318

**Pull request closed without merging**
