### PR TITLE
Updated the way `distinct_on` is processed internally

### PR DESCRIPTION
**Pull request by Cobular**
## PR Info

- Closes https://github.com/SeaQL/sea-query/issues/449

- Dependencies:
  - None

- Dependents:
  - None

## Fixes

- [x] Behavior of `distinct_on` with more complex cases of `ColumnRef`

## Breaking Changes

- [x] I don't believe so?

## Changes

- [x] Updated the `DistinctOn` case of the `SelectDistinct` enum to contain a vec of `ColumnRef` instead of `DynIden`
- [x] Modified `prepare_select_distinct` in backend/postgres/query.rs to use this new typing

### CODE REVIEW

**Comment by Cobular** [comment]
Unsure how to test this in my integration as `0.26.3` seems to have a pretty different internal structure - I may want to PR this against that as well so I can use this change on my project before 0.27.0 releases.

**Comment by billy1624** [comment]
Hey @Cobular, I think you can backport the changes to your own 0.26.3 branch then depends on it before 0.27 get released.

**Review by billy1624 — APPROVED** [review]
Hey @Cobular, thanks for the contributing a quick fix!! :)

**Review by ikrivosheev — COMMENTED** [review]
@Cobular hello! Thank you for PR. Can you run rustfmt?

**Comment by Cobular** [comment]
> Hey @Cobular, I think you can backport the changes to your own 0.26.3 branch then depends on it before 0.27 get released.

Sounds good!



> @Cobular hello! Thank you for PR. Can you run rustfmt?

Will do 🤦🏻‍♀️

**Comment by Cobular** [comment]
Getting this since I'm not on nightly:

image

If I switch, I update `src/expr.rs` with the following patch:

```patch
diff --git a/src/expr.rs b/src/expr.rs
index 17be24f..b445fe0 100644
--- a/src/expr.rs
+++ b/src/expr.rs
@@ -1913,19 +1913,14 @@ impl Expr {
     /// # Examples
     ///
     /// ```
-    /// use sea_query::{*, tests_cfg::*};
+    /// use sea_query::{tests_cfg::*, *};
     ///
     /// let query = Query::select()
     ///     .column(Char::Id)
     ///     .from(Char::Table)
-    ///     .and_where(
-    ///         Expr::col(Char::Id)
-    ///             .eq(
-    ///                 Expr::any(
-    ///                     Query::select().column(Char::Id).from(Char::Table).take()
-    ///                 )
-    ///             )
-    ///     )
+    ///     .and_where(Expr::col(Char::Id).eq(Expr::any(
+    ///         Query::select().column(Char::Id).from(Char::Table).take(),
+    ///     )))
     ///     .to_owned();
     ///
     /// assert_eq!(
@@ -1949,19 +1944,14 @@ impl Expr {
     /// # Examples
     ///
     /// ```
-    /// use sea_query::{*, tests_cfg::*};
+    /// use sea_query::{tests_cfg::*, *};
     ///
     /// let query = Query::select()
     ///     .column(Char::Id)
     ///     .from(Char::Table)
-    ///     .and_where(
-    ///         Expr::col(Char::Id)
-    ///             .ne(
-    ///                 Expr::some(
-    ///                     Query::select().column(Char::Id).from(Char::Table).take()
-    ///                 )
-    ///             )
-    ///     )
+    ///     .and_where(Expr::col(Char::Id).ne(Expr::some(
+    ///         Query::select().column(Char::Id).from(Char::Table).take(),
+    ///     )))
     ///     .to_owned();
     ///
     /// assert_eq!(
@@ -2239,14 +2229,11 @@ impl Expr {
     /// # Examples
     ///
     /// ```
-    /// use sea_query::{Query, Expr, PostgresQueryBuilder, MysqlQueryBuilder, SqliteQueryBuilder};
+    /// use sea_query::{Expr, MysqlQueryBuilder, PostgresQueryBuilder, Query, SqliteQueryBuilder};
     ///
     /// let query = Query::select().expr(Expr::current_date()).to_owned();
     ///
-    /// assert_eq!(
-    ///     query.to_string(MysqlQueryBuilder),
-    ///     r#"SELECT CURRENT_DATE"#
-    /// );
+    /// assert_eq!(query.to_string(MysqlQueryBuilder), r#"SELECT CURRENT_DATE"#);
     /// assert_eq!(
     ///     query.to_string(PostgresQueryBuilder),
     ///     r#"SELECT CURRENT_DATE"#
@@ -2265,14 +2252,11 @@ impl Expr {
     /// # Examples
     ///
     /// ```
-    /// use sea_query::{Query, Expr, PostgresQueryBuilder, MysqlQueryBuilder, SqliteQueryBuilder};
+    /// use sea_query::{Expr, MysqlQueryBuilder, PostgresQueryBuilder, Query, SqliteQueryBuilder};
     ///
     /// let query = Query::select().expr(Expr::current_time()).to_owned();
     ///
-    /// assert_eq!(
-    ///     query.to_string(MysqlQueryBuilder),
-    ///     r#"SELECT CURRENT_TIME"#
-    /// );
+    /// assert_eq!(query.to_string(MysqlQueryBuilder), r#"SELECT CURRENT_TIME"#);
     /// assert_eq!(
     ///     query.to_string(PostgresQueryBuilder),
     ///     r#"SELECT CURRENT_TIME"#
@@ -2291,7 +2275,7 @@ impl Expr {
     /// # Examples
     ///
     /// ```
-    /// use sea_query::{Query, Expr, PostgresQueryBuilder, MysqlQueryBuilder, SqliteQueryBuilder};
+    /// use sea_query::{Expr, MysqlQueryBuilder, PostgresQueryBuilder, Query, SqliteQueryBuilder};
     ///
     /// let query = Query::select().expr(Expr::current_timestamp()).to_owned();
     ///
```

**Want me to push this as well?**

**Comment by tyt2y3** [comment]
Sad, seems like I can't base this branch on 0.26, so backporting would be harder

**Comment by Cobular** [comment]
I actually have a backported branch on my repo - https://github.com/Cobular/sea-query/tree/0.26.4

I'll send a patch from whatever commit you want, what should I use as the base ref?

**Comment by billy1624** [comment]
Hey @Cobular, could you branch off from this, https://github.com/SeaQL/sea-query/tree/0.26.x, then maybe submit a new PR for this same fixup but merge into `0.26.x`? Thanks!!

**Review by ikrivosheev — APPROVED** [review]
@Cobular thank you! For me look cool!

**Comment by tyt2y3** [comment]
thank you

**Comment by Cobular** [comment]
Thank you for finalizing this!

**Comment by tyt2y3** [comment]
Yes can do a 0.26.4 somewhen this week

**Comment by Cobular** [comment]
I can PR into 0.26 if you'd like, the file got reorganized a bit at some point in the past so I'm not certain if a cherry pick is possible. Can you let me know if a cherry pick works?

**Comment by ikrivosheev** [comment]
@Cobular hello! I make PR with backport your changes: https://github.com/SeaQL/sea-query/pull/470

**Comment by tyt2y3** [comment]
https://github.com/SeaQL/sea-query/releases/tag/0.26.4

**Comment by Cobular** [comment]
Thank you so much for getting this finalized and fixed so quickly!!

**Pull request merged**
