### PR TITLE
SQLite does not support "LATERAL join"

### PR DESCRIPTION
**Pull request by billy1624**
## PR Info
- Will panic when building SQLite select with "LATERAL join"
- Continue of #224

### CODE REVIEW

**Review by rex-remind101 — APPROVED** [review]
excellent, thank you

**Comment by tyt2y3** [comment]
I don't know how we should deal with serialization errors. Seems like we need a `Result` interface instead of panics

**Comment by rex-remind101** [comment]
Wondering if there was any follow up here?

**Comment by billy1624** [comment]
> I don't know how we should deal with serialization errors. Seems like we need a `Result` based API instead of panics

This would be a major breaking change across SeaQuery.

> Wondering if there was any follow up here?

I think we can leave it as is for now? We already added a line in the docs saying this is not supported by SQLite.

https://docs.rs/sea-query/0.22.0/sea_query/query/struct.SelectStatement.html#method.join_lateral

**Pull request closed without merging**
