### PR TITLE
 issues-383 Create new crate for rusqlite

### PR DESCRIPTION
**Pull request by ikrivosheev**
## PR Info

- Closes https://github.com/SeaQL/sea-query/issues/383

- Dependencies:
  - https://github.com/SeaQL/sea-query/pull/416

## Adds

- Add new crate like sea-query-binder for rusqlite.

Continue work on: https://github.com/SeaQL/sea-query/pull/388

### CODE REVIEW

**Comment by ikrivosheev** [comment]
@tyt2y3 @billy1624 for me looks better naming: `sea-query-sqlx`, `sea-query-rusqlite`. Name is shorter. Explicitly says to which driver this binding is

**Comment by billy1624** [comment]
> @tyt2y3 @billy1624 for me looks better naming: `sea-query-sqlx`, `sea-query-rusqlite`. Name is shorter. Explicitly says to which driver this binding is

I agree. But the problem is that should we rename `sea-query-binder` to `sea-query-slqx`? And, how can we rename it (since it has been published to crates.io)?

I guess we could add a deprecated message at `sea-query-binder/lib.rs`?
```rs
#![deprecated(
    since = "0.1.0",
    note="The `sea-query-binder` crate has been renamed to `sea-query-sqlx`. Please update your dependency accordingly"
)]
```

Ideas? @tyt2y3

**Comment by ikrivosheev** [comment]
> > @tyt2y3 @billy1624 for me looks better naming: `sea-query-sqlx`, `sea-query-rusqlite`. Name is shorter. Explicitly says to which driver this binding is
> 
> I agree. But the problem is that should we rename `sea-query-binder` to `sea-query-slqx`? And, how can we rename it (since it has been published to crates.io)?
> 
> I guess we could add a deprecated message at `sea-query-binder/lib.rs`?
> 
> ```rust
> #![deprecated(
>     since = "0.1.0",
>     note="The `sea-query-binder` crate has been renamed to `sea-query-sqlx`. Please update your dependency accordingly"
> )]
> ```
> 
> Basically, we publish `sea-query-sqlx` on crates.io and no longer publish newer version under the name of `sea-query-binder`.
> 
> Ideas? @tyt2y3

I can copy-paste `sea-query-binder` with new name: `sea-query-sqlx`, add deprecated warning in `sea-query-binder` and after some time we can remove the folder.

**Comment by ikrivosheev** [comment]
@tyt2y3 I fixed all merge conflicts.

**Pull request merged**
