### PR TITLE
Bind array values in SQLx PostgreSQL driver

### PR DESCRIPTION
**Pull request by billy1624**
## PR Info
- Continue #205
- Fixing SeaQL/sea-query@67a8ffba1351c754aae2559051930d4fe2fe70ae

### CODE REVIEW

**Comment by tyt2y3** [comment]
Ah, so we still have to clone the values :(
But yea, it's so elaborate

**Comment by billy1624** [comment]
> Ah, so we still have to clone the values :( But yea, it's so elaborate

I can't think of a better way of doing it... given the defined `Value::array`

**Comment by tyt2y3** [comment]
It would be slightly if we introduce a separate function that takes ownership of Values

**Comment by billy1624** [comment]
> It would be slightly better if we introduce a separate function that takes ownership of Values

When binding the `value` onto SQLx query? Currently, it's taking `value` as reference.

**Comment by tyt2y3** [comment]
I think this will need to updated after merging https://github.com/SeaQL/sea-query/pull/267
It seems like a considerable maintenance cost in one sense

**Comment by itsbalamurali** [comment]
@billy1624 @tyt2y3 since #267 is merged. Can this be rebased and merged?

**Comment by ammongit** [comment]
Exciting! Glad to see array work progress.

**Comment by ikrivosheev** [comment]
@billy1624 Do you need help with this PR?

**Comment by ammongit** [comment]
Is there anything blocking this PR from being merged?

**Comment by tyt2y3** [comment]
Apart from the merge conflict, I'd appreciate if we can figure out a less verbose approach at supporting this.
The problem is when we add a new type variant to `Value`, it seems like that a lot has to be changed, and we have no compile-time check / CI that can catch those.
Basically a maintainability problem.

**Comment by negezor** [comment]
@billy1624 Is change needed here?
https://github.com/SeaQL/sea-query/blob/master/sea-query-driver/src/sqlx_postgres.rs#L59-L63

**Comment by negezor** [comment]
@billy1624 Is change needed here?
https://github.com/SeaQL/sea-query/blob/master/sea-query-driver/src/sqlx_postgres.rs#L59-L63

**Comment by kudlatyamroth** [comment]
maybe it is better to implement this in that form, and in future refactor it?
i think that many ppl needs this functionality

**Comment by Sytten** [comment]
Indeed I am in need of it so anything I can do to help let me know.

**Comment by billy1624** [comment]
Hey @Sytten @tyt2y3, I think we could dump this PR and start working on this feature from master, i.e. based on `sea-query-binder`.

**Comment by billy1624** [comment]
Would you like to take on this? @Sytten

**Comment by Sytten** [comment]
Yeah will do

**Comment by billy1624** [comment]
Thanks! @Sytten
Do let me know if you need help :D

**Pull request closed without merging**
