### PR TITLE
Helper methods for sea-orm soft delete

### PR DESCRIPTION
**Pull request by billy1624**
- Depended by SeaQL/sea-orm#276

### CODE REVIEW

**Comment by ikrivosheev** [comment]
@billy1624 can you fix `clippy warnings`? I think this is very useful.

**Comment by ikrivosheev** [comment]
@billy1624 do you plan to continue working?

**Comment by tyt2y3** [comment]
Actually, I would prefer a non-mut style of API: instead of `fn merge(&mut self, b)`, `fn merge(&self, b) -> Self` would be better.

**Comment by billy1624** [comment]
This is no longer needed in the updated soft delete https://github.com/SeaQL/sea-orm/pull/790
I'll close this

**Pull request closed without merging**
