### PR TITLE
support partial index

### LINKED ISSUE #396: Support for partial index
### Discussed in https://github.com/SeaQL/sea-orm/issues/872

<div type='discussions-op-text'>

<sup>Originally posted by **@onichandame**</sup>

## Motivation

Sqlite supports a `WHERE` clause on creating an index. [see docs](https://www.sqlite.org/partialindex.html)

This feature is useful if only a subset of rows need to be indexed. Without it the index must cover all rows, which unnecessarily consumes more disk space.

## Proposed Solutions

Something like `sea_query::Index::create().filter(<Condition>)` for use with entities, and `sea_query::Index::create().filter_raw("<Where Clause>")` for more freedom.

### PR DESCRIPTION
**Pull request by kyoto7250**
## PR Info
close #396
We supports partial index by this PR.

## Adds

- [x] support partial index.
  * [x] resolve conflict
  * [x] check comment
## Related

https://github.com/SeaQL/sea-query/pull/405 (original PR)

### CODE REVIEW

**Review by ikrivosheev — APPROVED** [review]
@kyoto7250 thank you! LGTM!

**Comment by ikrivosheev** [comment]
@kyoto7250 is this PR ready?)

**Comment by kyoto7250** [comment]
@ikrivosheev  Thank you for your quick reply :)

I want to confirm that this PR works as expected in the database at hand (not yet confirmed, so this PR is a WIP.)

**Comment by ikrivosheev** [comment]
@kyoto7250 any updates?)

**Review by billy1624 — COMMENTED** [review]
Hey @kyoto7250, I highly recommend this site for testing SQL syntax across various databases :)

**Comment by ikrivosheev** [comment]
> Hey @kyoto7250, I highly recommend this site for testing SQL syntax across various databases :)

@billy1624 which site do you mean?

**Comment by billy1624** [comment]
@ikrivosheev Good question!! I forgot to post the link loll

**Comment by ikrivosheev** [comment]
@kyoto7250 hello, any updates?)

**Comment by wolfv** [comment]
We would love to see this feature land, too! :)

**Comment by tyt2y3** [comment]
Glad that you are back! Apart from the conflicts, I think we can still merge this PR.

**Comment by IgnisDa** [comment]
Hey @tyt2y3 any updates on this? I need this feature.

**Comment by kyoto7250** [comment]
I made the  PR  for fixing failed CI.

https://github.com/SeaQL/sea-query/pull/718

**Comment by kyoto7250** [comment]
After rebasing, I increased the version of `bigdecimals` so that the build would succeed.

**Comment by kyoto7250** [comment]
This PR is now available for review.

**Comment by kyoto7250** [comment]
@billy1624  @ikrivosheev 
Sorry for the long delay in correcting the PR.
Could you give me your review?

**Review by tyt2y3 — APPROVED** [review]

**Pull request merged**
