### PR TITLE
issues-383 Improve sea-query-binder

### PR DESCRIPTION
**Pull request by ikrivosheev**
## PR Info

- Closes https://github.com/SeaQL/sea-query/issues/383

- Dependents:
  - https://github.com/SeaQL/sea-orm/pull/970

## Adds

- Add `sqlx` runtime features
- Split `sea-query-binder` and `sea-query` to different workspace
- Move examples to another workspace
- Rewrite CI

### CODE REVIEW

**Comment by ikrivosheev** [comment]
@billy1624 @tyt2y3 if these changes are ok, I can fix CI.

**Comment by tyt2y3** [comment]
Yes they are OK

**Comment by ikrivosheev** [comment]
@tyt2y3 @billy1624 hello! Done!

**Review by billy1624 — COMMENTED** [review]
Thanks!! @ikrivosheev

Some comments on the CI https://github.com/SeaQL/sea-query/issues/383#issuecomment-1223866255

**Comment by ikrivosheev** [comment]
@billy1624 hello!

- [x] - https://github.com/SeaQL/sea-query/issues/383#issuecomment-1223866255
- [x] - https://github.com/SeaQL/sea-query/issues/383#issuecomment-1223875932

**Review by billy1624 — APPROVED** [review]
Thanks!! @ikrivosheev The CI looks good!

**Comment by tyt2y3** [comment]
Thank you guys

**Pull request merged**
