### PR TITLE
exclude chrono default-features

### PR DESCRIPTION
**Pull request by robjtede**
in an effort to remove time v0.1 from the dep graph

### CODE REVIEW

**Review by robjtede — COMMENTED** [review]
(oops did this in github.dev by accident)

**Comment by ikrivosheev** [comment]
@robjtede, hello! Can you explane, what you want?

**Comment by robjtede** [comment]
`cargo audit` compains about vulnerabilities in time v0.1 which is enabled transitively via chrono when the `oldtime` feature is enabled. This PR disables that feature of chrono.

**Review by billy1624 — COMMENTED** [review]
Hey @robjtede, thanks for the auditing!

Same here :)
I would suggest pinning the version to `^0.4` insead of `^0`

**Comment by robjtede** [comment]
>  I would suggest pinning the version to ^0.4 insead of ^0

yep so would I but i've left them all as they were since it's not the purpose of this PR

**Comment by billy1624** [comment]
Oh... sorry I thought it was `^0.4` but in fact originally it's `^0`

**Comment by tyt2y3** [comment]
Thank you for letting us know @robjtede

**Pull request merged**
