### PR TITLE
Making pagination efficient with `first` function.

### PR DESCRIPTION
**Pull request by arpancodes**
## PR Info

- Closes  https://github.com/SeaQL/sea-orm/issues/300

- Dependencies:
  - This PR will help optimise the `fetch_page` in https://github.com/SeaQL/sea-orm

## Adds
- `first` function to the `SelectStatement` struct.
- Corresponding tests for `mysql`, `postgres` and `sqlite`

## Improves
This will improve the pagination.

### CODE REVIEW

**Comment by tyt2y3** [comment]
I think this PR is opened at the wrong repo. `first` essentially is same as `limit`.
It is more logical to put it in the SeaORM's `Selector*` API, although if needed you can also add some features to sea-query.

**Comment by arpancodes** [comment]
Should I create a new function in `paginator.rs` @tyt2y3?

**Comment by ikrivosheev** [comment]
@tyt2y3 @arpancodes I think we can close this PR?

**Comment by tyt2y3** [comment]
> I think we can close this PR?

Agreed

**Pull request closed without merging**
