### PR TITLE
Refactoring

### PR DESCRIPTION
**Pull request by ikrivosheev**
I am continue working on improve `API` 

## New Features

- Added `Expr::custom_keyword`
- Added `SimpleExpr::not`

## Breaking changes

- MSRV is up to 1.62 

## Changes

- Replace `impl Default` to `#[derive(Default)]`

### CODE REVIEW

**Comment by tyt2y3** [comment]
Just being curious, what feature do we need from `1.62`?

**Review by tyt2y3 — APPROVED** [review]
Looks nice

**Comment by billy1624** [comment]
> Just being curious, what feature do we need from `1.62`?

We shouldn't bump MSRV simply because a new version of Rust is being released. MSRV should be kept to the minimum compatible version.

And Rust compiler will throw a seemingly unrelated error message when user compile the project with older Rust version. E.g. https://github.com/SeaQL/sea-orm/issues/1045

**Comment by billy1624** [comment]
Btw... we have this tool to find the minimum compatible Rust version: https://github.com/foresterre/cargo-msrv

**Comment by ikrivosheev** [comment]
> Just being curious, what feature do we need from `1.62`?

@tyt2y3 I need it for https://rust-lang.github.io/rfcs/3107-derive-default-enum.html

**Comment by billy1624** [comment]
Bumping MSRV in SeaQuery means bumping MSRV across nearly all SeaQL libraries. As SeaQuery is the foundation of everything.

**Comment by ikrivosheev** [comment]
I understand this. 

1. SeaORM - https://github.com/SeaQL/sea-orm/blob/master/Cargo.toml#L16 (MSVR 1.65)
2. SeaSchema haven't this - https://github.com/SeaQL/sea-schema/blob/master/Cargo.toml

**Review by billy1624 — APPROVED** [review]
Hey @ikrivosheev, thanks for the quick check!!
We should specify the MSRV in SeaSchema after this was merged

**Pull request merged**
